### ISSUE TITLE
high frequency handlers

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_to_cmip#129]
Right now, E2C accept pr_highfreq and rlut_highfreq as input variable names at sub-monthly frequency. 
(day, 3hr) pr_highfreq
(day) rlut_highfreq
 
pr_highfreq and rlut_highfreq match handler conversion scripts names. A cleaner way is to let E2C to distribute handlers based on input for frequency. A more advanced scheme is to have a list of handlers, and E2C can loop over the handlers and identify the proper one based on available available variables, something similar to the derived variable function from e3sm_diags (https://github.com/E3SM-Project/e3sm_diags/blob/master/e3sm_diags/derivations/acme.py)

**Comment by TonyB9000** [comment]
I note here what I've learned about the need to distinguish (for instance) "pr" and "pr_highfreq" in the e3sm_warehouse job codes.  Key is the fact that a dataset may not use the "_highfreq" designation in the dataset_id.  Its appearance, where needed, must be inferred from the frequency (day, 3hr).

The e3sm_warehouse jobs call "e3sm_to_cmip" twice when processing a dataset.  First, with the "--info" flag to obtain variable info (used to forge a config file for a subsequent cwltool workflow call) and later as a component of that cwltool workflow to perform the actual cmorizing.  The job begins by receiving the dataset_id for the dataset to be produced.

The first (--info) call to e2c (assuming a sub-monthly case) must supply the "pr_highfreq" name in the variable list so that the correct variable info is returned (includes requisite E3SM variables, conversion formula).  So the job must seek (pr, rlut) obtained from the dataset_id, and convert to add the "_highfreq" suffix.  Even here, however, the returned variable info includes a value "CMIP6_Name" which is still "pr", not "pr_highfreq".  As our codes use these returned CMIP6_Names to form the variable list for the second e2c call (via cwltool workflow), it must _again_ be identified and converted to append "_highfreq".

The "info" returned on the first pass is used in the cwltool workflow to conduct the regridding and timeseries generation from the native data, so that it may be supplied as input to the cmorizing in the latter steps of the cwltool workflow.  But aside from this need, it does seem as if I must obtain "info" from e2c in the first call, and then supply this back to e2c in a subsequent call.  That may be an unfair characterization - but it seems as if e2c, armed with the frequency, could better isolate the "_highfreq"/not-"_highfreq" disparity internally, rather than have external processes juggle with it.  Perhaps there are side-effects of which I am unaware.
