### ISSUE TITLE
Previously unseen error "pcode: {pcode} is not supported."

### ISSUE THREAD

**Issue by strandwg** [E3SM-Project/e3sm_to_cmip#163]
We're using e3sm_to_cmip to convert some MPAS monthly mean ocean data from E3SMv2 to CMIP6-compliant format, and while the code works fine for me, a colleague gets the error

pcode: {pcode} is not supported.

for 20 of the 26 fields expected. The only fields generated are masso soga sosga thetaoga tosga volo; the fields that end up being single values at each time.

I've not seen this error before.

We're running on cori.nersc.gov.

Script is at

~sglanvil/SSP370_111_Omon.sh

output is at

~sglanvil/Omon_SSP111.64250777.err

and

~sglanvil/Omon_SSP111.64250777.out

Thanks for any assistance!

**Comment by chengzhuzhang** [comment]
Hi @strandwg Thank you for reporting the error! The issue with `pcode: {pcode} is not supported.` is fixed in the commit https://github.com/E3SM-Project/e3sm_to_cmip/pull/158
I'm wondering your colleague may use an old version that doesn't have this fix. To update the code using master branch should resolve this issue.

**Comment by chengzhuzhang** [comment]
@strandwg I would like to add that the latest master also support MPAS sea-ice variables generation. Please let us know if you find any issues. Thank you.

**Comment by strandwg** [comment]
She installed e3sm_to_cmip on Friday 11 November; the e3sm_to_cmip is version 1.9.0 - I'll ask her to repeat the install.

Thanks!

**Comment by chengzhuzhang** [comment]
fixed in the commit https://github.com/E3SM-Project/e3sm_to_cmip/pull/158
